[GLOBAL]
; Mirakurun(Mirac)を実行しているサーバのIPアドレス(同じDocker compose環境ならサービス名でも可)
SERVER_HOST="mirakurun"
SERVER_PORT=40772

; SERVER_SOCKPATH="/var/run/mirakc.sock"

; "http" or "unix"
SERVER_TYPE="http"

; B25(1=enable)
DECODE_B25=1

; Priority(0=Low Priority) 10 by default
PRIORITY=0

; サービスを分割するか
;   0: 分割しない (すべてのサービスを出力)
;   1: 分割する (指定されたサービスのみを出力・デフォルト)
SERVICE_SPLIT=0
