[SET]
RecFolderNum=1
RecFolder0=/rec
NGEpgCapTime=0
NGEpgCapTunerTime=0
CompatFlags=128
RecEndMode=0
Data=1
SaveDebugLog=0
RecInfo2RegExp=\[[^\]]+\]|[【［][^】］]+[】］]|🈑|🈞|🈡|🈢|🈚

HttpEnableIPv6=0
HttpAccessControlList=+127.0.0.1,+10.0.0.0/8,+172.16.0.0/12,+192.168.0.0/16,+100.64.0.0/10
EnableHttpSrv=2

EnableTCPSrv=1
TCPAccessControlList=+127.0.0.1,+10.0.0.0/8,+172.16.0.0/12,+192.168.0.0/16,+100.64.0.0/10
TCPPort=4510

[SET_TCP]
Count=1
IP0=1
Port0=22000

[BonDriver_LinuxMirakc.so]
Count=2
GetEpg=1
EPGCount=1
Priority=0

[BonDriver_LinuxMirakc(LinuxMirakc).so]
; チューナーの数に応じて変更
Count=2
; GetEpgはチューナー数の半分目安
GetEpg=1
EPGCount=1
Priority=0

[TVTEST]
Num=1
0=BonDriver_LinuxMirakc.so

[EPG_CAP]
Count=2
0=04:00
0Select=1
0BasicOnlyFlags=-1
1=19:00
1Select=1
1BasicOnlyFlags=-1

